name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    name: Typecheck (TS) and Lint/Test (Rust)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install JS dependencies
        run: bun install --frozen-lockfile

      - name: Typecheck frontend
        run: |
          bun x tsc --noEmit

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust fmt check
        run: cargo fmt --manifest-path src-tauri/Cargo.toml --all -- --check

      - name: Rust clippy
        run: cargo clippy --manifest-path src-tauri/Cargo.toml --all-targets -- -D warnings

      - name: Rust tests
        run: cargo test --manifest-path src-tauri/Cargo.toml --all --verbose
